properties:
  aggregateWindow:
    properties:
      fillValues:
        type: boolean
      period:
        type: string
    type: object
  buckets:
    items:
      type: string
    type: array
  functions:
    items:
      $ref: ./BuilderFunctionsType.yaml
    type: array
  tags:
    items:
      $ref: ./BuilderTagsType.yaml
    type: array
type: object
